#!/usr/bin/env python

import sys, string
from fcla import InOutBoard, INOUT_URL
from optparse import OptionParser

# Process Command Line arguments
usage = "usage: %prog [options] I[N] | O[UT]"
parser = OptionParser(usage=usage)
parser.add_option("-m", "--message", dest="message", metavar="MESSAGE",
                  help="a message to put on the in/out board")

parser.add_option("-v", "--verbose", 
                  action="store_true", dest="verbose", default=False,
                  help="increase verbosity")
		  	    	   
parser.set_defaults(message='')
(options, args) = parser.parse_args(sys.argv)

if len(args) != 2:
  parser.error("must specify only IN or OUT")

status = string.lower(args[-1])

if not status in ['in', 'out']:
  parser.error("must specify only IN or OUT")

# log if verbosity is active
def log(entry):
  if options.verbose:
    print entry

# make an in out board connection
try:
  board = InOutBoard(INOUT_URL)
  log('Connected to %s' % INOUT_URL)
except IOError:
  sys.stderr.write('Error: cannot connect to the in/out board at %s, is it down?\n' % INOUT_URL)
  sys.exit(1)

# sign in
if status == 'in':
  log('Signing in')
  board.mark_in(options.message)
elif status == 'out':
  log('Siging out')
  board.mark_out(options.message)
